### ISSUE TITLE
[Feature Request] Add support for webhooks built with workflows builder

### ISSUE THREAD

**Issue by pzaj2** [severisv/SlackLogger#30]
Hi,

Since incoming webhooks are deprecated, I thought that it'd be great if this library also supported webhooks that were built with Slack App workflows builder.

Currently, if you point the logger to a webhook URL from a workflow, you'll see something similar to
![image](https://user-images.githubusercontent.com/19946083/186172967-8b9507b9-6c5c-4763-bb95-4294be3effbe.png)
As opposed to a nicely formatted message.

**Comment by severisv** [comment]
I'm not familiar with the workflow builder, but I can have a look when I have time. Surely the logger should be up to date with the appropriate ways of integrating with Slack! 

Would you mind describing briefly how you are using it with the Workflow Builder?

**Comment by pzaj2** [comment]
I literally use it the way it's described here: https://slack.com/intl/en-gb/help/articles/360041352714-Create-more-advanced-workflows-using-webhooks

You set up a webhook with one variable - `text` - and then use "Send a message" step, using the variable in the message (the message is required by the step). What you see on the screenshot is the result - the "channel" notification does not work properly (it's inserted in the message as a literal) and attachments are ignored.

I couldn't find any consistent and reliable information on how to add notifications to the message and how to make attachments work. I only had so much time to look into it though, so I may have just as well missed an obvious solution waiting to be discovered.

**Comment by severisv** [comment]
Thanks for elaborating - it sounds to me like you might be just as well off with a webhook from a [Slack App](https://api.slack.com/messaging/webhooks)?

This should still work well, however the configuration options of choosing name, channel and icon will no longer work.

I'm not sure if it makes sense to use this library as part of a Workflow Builder flow? I plan to adapt it to use the newer version of the webhook api - if that also makes it compatible with the Workflow Builder that would be a nice side effect, but it doesn't seem like a priority (unless I'm conviced otherwise).

A priority should be to update the docs to make sure it's easy to configure the Slack integration correctly though - thanks for reporting! ☺

**Comment by severisv** [comment]
I've updated the readme to describe how to integrate. Closing this until I see the point of supporting Workflows Builder
